### ISSUE TITLE
Error in running battery_storage files.

### ISSUE THREAD

**Issue by parimuns** [locuslab/e2e-model-learning#9]
Hello I am trying to run the main.py file of battery_storage  and I am getting size issue as attached below.

`C:\Users\AppData\Local\Programs\Python\Python37\Scripts\battery_storage>main.py --save   C:\Users\AppData\Local\Programs\Python\Python37\Scripts\battery_storage  --nRuns 1  --paramSet 1
C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\loss.py:445: UserWarning: Using a target size (torch.Size([500, 24])) that is different to the input size (torch.Size([500, 24])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python37\Scripts\battery_storage\main.py", line 234, in <module>
    main()
  File "C:\Users\AppData\Local\Programs\Python\Python37\Scripts\battery_storage\main.py", line 73, in main
    model_rmse = nets.run_rmse_net(model_rmse, loaders_task, params, tensors_task)
  File "C:\Users\AppData\Local\Programs\Python\Python37\Scripts\battery_storage\nets.py", line 55, in run_rmse_net
    total_train_loss += train_loss.data[0] * X_train_.size(0)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number`

**Comment by priyald17** [comment]
I have updated the code to use the newest version of PyTorch (76d19e49c145f1d8721d58e7bf74719b59a38480), which should hopefully resolve this issue.
